### PR TITLE
please consider adding regions for russia

### PR DESCRIPTION
**Pull request by bazilek**
- minor typo fixed
- rebased on https://github.com/abh/geodns/pull/91 please merge it first

### CODE REVIEW

**Comment by abh** [comment]
Looks good; thank you! The typo is pretty crazy; I can't believe I did that. I'll look again this weekend with less blurry eyes and merge.

**Comment by suedadam** [comment]
Was this tested as of yet? Reading it with some tired eyes I see it having a potential issue 

`if country != "us" && country != "ru" {`
Shouldn't this be OR rather than AND? (|| instead of &&)?

**Comment by abligh** [comment]
OR cannot be correct, as

    country != "us" || country != "ru"

is logically always true.

    country != "us" && country != "ru"

is only true if `country` is neither 'us' or 'ru'.

> On 22 Feb 2017, at 03:28, Adam Syed <notifications@github.com> wrote:
> 
> Was this tested as of yet? Reading it with some tired eyes I see it having a potential issue
> 
> if country != "us" && country != "ru" {
> Shouldn't this be OR rather than AND? (|| instead of &&)?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Alex Bligh

**Comment by suedadam** [comment]
Right haha, tired eyes

**Comment by mkasimd** [comment]
Which district does `ru-ufd` refer to? The North Caucasian? If so, doesn't `ru-ncfd` make more sense?

**Comment by bazilek** [comment]
> Which district does `ru-ufd` refer to? The North Caucasian? If so, doesn't `ru-ncfd` make more sense?

_Ural Federal District_ according to the link in the source

**Comment by mkasimd** [comment]
> Ural Federal District according to the link in the source

`ru-ufd` is in the following lines

line 88 - 93
```
"ru-01": "ru-ufd",
"ru-07": "ru-ufd",
"ru-84": "ru-ufd",
"ru-24": "ru-ufd",
"ru-38": "ru-ufd",
"ru-61": "ru-ufd",
```

The Urals however are in the following lines

line 136 - 142:
```
"ru-40": "ru-uralfd",
"ru-71": "ru-uralfd",
"ru-78": "ru-uralfd",
"ru-32": "ru-uralfd",
"ru-13": "ru-uralfd",
"ru-87": "ru-uralfd",
```

Furthermore, the North Caucasian District is missing

**Comment by abh** [comment]
The list came from MaxMind (and might need updating). It needs to be in sync with the data they use in the GeoIP databases.

**Comment by bazilek** [comment]
@mkasimd 
Please consider this commit with fixed typo in names 
 https://github.com/bazilek/geodns/commit/4fa571801eb5e78691a1896c29a0d57f8305b280

**Comment by abh** [comment]
@bazilek any chance you'd send an update with with GeoIP2 regions? I've made a few other fixes and made sure the tests are working again.

**Comment by bazilek** [comment]
geoip2 compatible federal regions of russia in https://github.com/bazilek/geodns/commit/671c2b43021ca5a6b07147dba1dc05ab9585928d

**Comment by abh** [comment]
Thanks, @bazilek !

**Pull request merged**
